name: audiometa
description: Read and write metadata of audiofiles in Dart.
version: 0.0.0
homepage: https://github.com/illright/audiometa
author: Lev Chelyadinov <leva181777@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  utf: ^0.9.0+5

dev_dependencies:
  test: ^1.5.1+1
